### ISSUE TITLE
"Request Entity Too Large" error

### ISSUE THREAD

**Issue by fnagel** [NamelessCoder/typo3-repository-client#12]
Github hook response:

```
{
    "messages": [
        "The following errors were reported:",
        "Request Entity Too Large (0)\n"
    ]
}
```

Any idea what to do against this? Seems to happen with big extensions as well as with tiny ones (talking of file amount and size). Could this be my server? Or Gitub? Just stopped working :-/

**Comment by NamelessCoder** [comment]
Hi Felix,

If possible could you dump the request that gets made and check for any obvious issues with the SOAP?

The only other thing I can think of at this moment is something changed in the request processing on the server, causing the SOAP requests that were previously valid length to now be rejected.

**Comment by NamelessCoder** [comment]
I assume you've seen https://github.com/NamelessCoder/typo3-repository-client/issues/6 and confirmed it's not cause?

**Comment by fnagel** [comment]
Never had any issues with excluding folders as described in #6. Today I releases three extensions, two failed, one worked. All three have been deployed to TER with the exact same configuration I'm using at the moment.

Here's a dump of `$payload` in `\fluidtypo3-gizzle\vendor\namelesscoder\gizzle\web\github-webhook.php` after `processSettingsFile` has finished: http://pastebin.com/0MSxNFWq

**Comment by NamelessCoder** [comment]
Nothing immediately wrong in that payload. I think this error is being thrown by TER itself and if it really is caused by the packed data being too large, debugging the Packer or Uploader from https://github.com/NamelessCoder/typo3-repository-client/tree/master/src might explain the issue. You might not see any issues if for example the `.git` folder git included, until the combined size of your repository files and git data exceed whichever limit TER imposes.

Knowing this limit would by the way be quite nice - if it is one of those values that doesn't change often. Knowing it in advance would allow the library to throw a more specific error before uploading.

**Comment by fnagel** [comment]
Here's another payload debug with runtime exception, perhaps a little more helful: http://pastebin.com/LXZ8Y4VT

**Comment by fnagel** [comment]
Mhh, I'm not aware of anything that would increase the filesize that much. IF the .git folder has been included in earlier version, would it be included in the TER release available at typo3.org? Because that seems not the case.

**Comment by NamelessCoder** [comment]
Yes, I think if it was uploaded it would be included - although it might not be downloaded unless the extension gets downloaded via EM or in .t3x format.

Error occurs where it would normally be expected if the upload request indeed was too big. Looking back at the source code now, it would exclude `.git` by default - but will include any files/folders not prefixed with a dot (which includes unit test folders, fixtures and whatnot).

You can debug the upload data you send to TER somewhere around https://github.com/NamelessCoder/typo3-repository-client/blob/master/src/ExtensionUploadPacker.php#L160. If that has a reasonable size then my only possible explanation is that something changed in the TER server which has lowered the maximum request size. It's been a while since I last released so I am not sure if/when anything changed.

**Comment by fnagel** [comment]
Just tried the latest (automated) release as t3x and it looks good. No unwanted folders. Compared the old 2.0.0 and the upcoming 2.0.1 release -- about 10KB bigger (603KB) :-/

Excluding dot folders sounds like a good idea. Parsing gitignore sounds pretty cool but seems over engineered. A simple configuration option should be enough.

Dumping the `$compier` var just shows empty class: 

```
object(NamelessCoder\TYPO3RepositoryClient\SoapDataCompiler)#24 (0) {
}
```

but the $extension var looks ok: http://pastebin.com/LTBhdnyK

Dumps of the `$extensionData` var or the return value of `$compier->createSoapData` seem to look fine and are about about 960 KB big saved to a file. Which sounds reasonable looking at my source code.

**Comment by fnagel** [comment]
Update: I've pushed another release of the same extension without problems. Before releasing this version I've crushed all documentation images and reduced the overall archive size by ~30% (408KB now) . Not sure if that did the trick but it's possible...

Closing this for now, we'll see if the issue occurs again. Thanks for your support!
